### ISSUE TITLE
Startup bug, help needed.

### ISSUE THREAD

**Issue by Leviyf** [EpicCash/epic-gui-wallet#36]
When I start up the Epic wallet it tells me "We found some running wallet and node processes in the background. Please close them first before you run this App." Then it will not allow me to login until, I exit the wallet and start it up again (then it works).

Steps to reproduce the behavior are, usually after the wallet has been closed for a few hours and I try to login, this occurs. (I am clueless if I have some sort of node running in the background. I thought I deleted all my old EPIC files and wallet.)

I expect to be able to login the first time without this bug occuring. However, I am a simpleton and so I could easily be screwing something up without knowing. I just got my first laptop like 3 months ago and I barely know how to use this thing lol.

 
![20220729_193632](https://user-images.githubusercontent.com/110196709/181863842-9602b2a5-a086-47c4-a9ea-35443dc60971.png)

 - Config toml file or command line 
 I do not know how to add a config toml or command line. I do not even really know what that is lol.

Windows 11

 - Node.js Version

Additional context:  I really hope I will not make solving this issue complicated or explaining this to me complicated because I am honestly clueless. Just opened a github account as well so I am new to this and not sure if I am documenting this correctly either. Maybe label this with a help needed label haha

**Comment by johanneshahn** [comment]
The app checks on boot if there are old background process which are not shutdown correct the last time.
Or if you have other processes running which conflicts with the wallet.

This process can be one of:
epic-wallet
epic server
ngrok
tor

then this prompt pops up. When you press OK, The wallet tries to quit this processes. 
Or you quit this process by hand and click cancel.

**Comment by Leviyf** [comment]
I think it is very possible I shut down my previous wallet in the wrong fashion. So how do I make sure that the previous wallet was shut down correctly? I deleted it already so what can I do to fix this?

**Comment by johanneshahn** [comment]
The wallet version 3.0 had problems to shutdown App processes. So it should be fixed.

**Comment by Leviyf** [comment]
So will it fix itself overtime or should I uninstall the 4.0 wallet and install again maybe? I tried restarting my laptop that did not fix it.
